name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, '3.9.0-rc.1 - 3.9.0']
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install poetry
      run: pip install 'poetry==1.1.0b2' wheel
    - name: Install deps
      run: poetry install
    - name: Code health
      run: poetry run python -m pytest --mypy --flake8 --isort --black pyventory/
    - name: Tests
      run: poetry run python -m pytest tests/
